Deploy Finish

diff --git a/.github/workflows/backend-test.yml b/.github/workflows/backend-test.yml
--- a/.github/workflows/backend-test.yml
+++ b/.github/workflows/backend-test.yml
@@ -43,12 +43,45 @@ jobs:
       - name: Run backend tests
         run: pytest test_api.py
         
-  deploy-render:
-    needs: test-backend
+
+  start_deploy_render:
+    name: Iniciar el despligue en Render
     runs-on: ubuntu-latest
-    if: success() # Solo si los tests pasan
+    needs: test-backend
+    if: github.event_name == 'push' && github.ref == 'refs/heads/DevOps' && success()
     steps:
-      - name: Deploy to Render
+      - name: Desplegar en Render
         run: |
-          curl -X POST "https://api.render.com/deploy/srv-d2hrs9je5dus73e37jeg?key=JS1m1dH6B6c" \
-          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.render.com/deploy/srv-cpfne37109ks73bnsccg?key=jnQgfSOiqgI")
+          if [ $response -eq 200 ]; then
+            echo "Deployment successful"
+          else
+            echo "Deployment failed with HTTP status code $response"
+            exit 1
+          fi
+        env:
+          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
+
+  deploy_in_process:
+    name: Despliegue en proceso
+    runs-on: ubuntu-latest
+    needs: start_deploy_render
+    if: github.event_name == 'push' && github.ref == 'refs/heads/DevOps' && success()
+    steps:
+      - name: Despliegue en proceso
+        run:  |
+          deploy_status="pending"
+          while [ "$deploy_status" != "live" ]; do
+            response=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" "https://api.render.com/v1/services/srv-cpfne37109ks73bnsccg/deploys")
+            echo "Render API response: $response"
+            deploy_status=$(echo $response | jq -r '.[0].deploy.status') 
+            echo "Current deploy status: $deploy_status"
+            if [ "$deploy_status" == "failed" ]; then
+              echo "Deployment failed."
+              exit 1
+            fi
+            sleep 5
+          done
+          echo "Deployment completed successfully."
+        env:
+          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
